package com.soubu.goldensteward.support.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "Address".
 */
@Entity(nameInDb = "Address")
public class Address {

    @Id(autoincrement = true)
    private Long id;
    private Integer area_id;
    private Integer parent_id;
    private String area_name;
    private Integer sort;
    private String tag;

    @Generated
    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    @Generated
    public Address(Long id, Integer area_id, Integer parent_id, String area_name, Integer sort, String tag) {
        this.id = id;
        this.area_id = area_id;
        this.parent_id = parent_id;
        this.area_name = area_name;
        this.sort = sort;
        this.tag = tag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArea_id() {
        return area_id;
    }

    public void setArea_id(Integer area_id) {
        this.area_id = area_id;
    }

    public Integer getParent_id() {
        return parent_id;
    }

    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    public String getArea_name() {
        return area_name;
    }

    public void setArea_name(String area_name) {
        this.area_name = area_name;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

}
