package com.soubu.goldensteward.base.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "User".
 */
@Entity(nameInDb = "User")
public class User {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String portrait;
    private String phone;
    private String main_product;
    private String province;
    private String province_id;
    private String city;
    private String city_id;
    private String address;
    private String contact_name;
    private String job;
    private String company;
    private String company_size;
    private String operation_mode;
    private String mail;
    private String main_industry;
    private String turnover;
    private String fixed_telephone;
    private String company_profile;
    private String uid;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String name, String portrait, String phone, String main_product, String province, String province_id, String city, String city_id, String address, String contact_name, String job, String company, String company_size, String operation_mode, String mail, String main_industry, String turnover, String fixed_telephone, String company_profile, String uid) {
        this.id = id;
        this.name = name;
        this.portrait = portrait;
        this.phone = phone;
        this.main_product = main_product;
        this.province = province;
        this.province_id = province_id;
        this.city = city;
        this.city_id = city_id;
        this.address = address;
        this.contact_name = contact_name;
        this.job = job;
        this.company = company;
        this.company_size = company_size;
        this.operation_mode = operation_mode;
        this.mail = mail;
        this.main_industry = main_industry;
        this.turnover = turnover;
        this.fixed_telephone = fixed_telephone;
        this.company_profile = company_profile;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortrait() {
        return portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMain_product() {
        return main_product;
    }

    public void setMain_product(String main_product) {
        this.main_product = main_product;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getProvince_id() {
        return province_id;
    }

    public void setProvince_id(String province_id) {
        this.province_id = province_id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCity_id() {
        return city_id;
    }

    public void setCity_id(String city_id) {
        this.city_id = city_id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getContact_name() {
        return contact_name;
    }

    public void setContact_name(String contact_name) {
        this.contact_name = contact_name;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getCompany_size() {
        return company_size;
    }

    public void setCompany_size(String company_size) {
        this.company_size = company_size;
    }

    public String getOperation_mode() {
        return operation_mode;
    }

    public void setOperation_mode(String operation_mode) {
        this.operation_mode = operation_mode;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getMain_industry() {
        return main_industry;
    }

    public void setMain_industry(String main_industry) {
        this.main_industry = main_industry;
    }

    public String getTurnover() {
        return turnover;
    }

    public void setTurnover(String turnover) {
        this.turnover = turnover;
    }

    public String getFixed_telephone() {
        return fixed_telephone;
    }

    public void setFixed_telephone(String fixed_telephone) {
        this.fixed_telephone = fixed_telephone;
    }

    public String getCompany_profile() {
        return company_profile;
    }

    public void setCompany_profile(String company_profile) {
        this.company_profile = company_profile;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

}
